[versions]
androidx-appcompat = "1.1.0"
androidx-core = "1.1.0"
androidx-constraintlayout = "1.1.3"
junit = "4.12"
androidx-test-runner = "1.2.0"
androidx-test-espresso = "3.2.0"
cardview = "28.0.0"
dagger = "2.24"
dagger-android = "2.23"
dagger-assisted-inject = "0.5.0"


[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
junit = { module = "junit:junit", version.ref = "junit" }
runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
cardview = { module = "com.android.support:cardview-v7", version.ref = "cardview" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger-android" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger-android" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger-android" }
assisted-inject-annotations-dagger2 = { module = "com.squareup.inject:assisted-inject-annotations-dagger2", version.ref = "dagger-assisted-inject" }
assisted-inject-processor-dagger2 = { module = "com.squareup.inject:assisted-inject-processor-dagger2", version.ref = "dagger-assisted-inject" }
